param(
    [string]$Profile = ""
)

if (-not $Profile) {
    Write-Host ""
    Write-Host "  ╔════════════════════════════════════════╗"
    Write-Host "  ║     Farewell Orchestra — Profiles      ║"
    Write-Host "  ╠════════════════════════════════════════╣"
    Write-Host "  ║  1. Pro      orchestrator=Pro          ║"
    Write-Host "  ║             workers=Flash              ║"
    Write-Host "  ║                                        ║"
    Write-Host "  ║  2. Flash    orchestrator=Flash        ║"
    Write-Host "  ║             workers=Free               ║"
    Write-Host "  ║                                        ║"
    Write-Host "  ║  3. Free     all Free (max hemat)      ║"
    Write-Host "  ║                                        ║"
    Write-Host "  ║  4. Custom   edit .env manual          ║"
    Write-Host "  ║             lalu run opencode          ║"
    Write-Host "  ╚════════════════════════════════════════╝"
    Write-Host ""
    $choice = Read-Host "  Pilih [1-4]"
    switch ($choice) {
        "1" { $Profile = "pro" }
        "2" { $Profile = "flash" }
        "3" { $Profile = "free" }
        "4" { $Profile = "custom" }
        default { Write-Host "Invalid choice"; Read-Host "Press Enter"; exit 1 }
    }
}

switch ($Profile) {
    "pro"    { $heavy = "ocg/deepseek-v4-pro";       $light = "ocg/deepseek-v4-flash";      Write-Host "  [Pro] orchestrator=Pro  |  workers=Flash" }
    "flash"  { $heavy = "ocg/deepseek-v4-flash";     $light = "oc/deepseek-v4-flash-free";  Write-Host "  [Flash] orchestrator=Flash  |  workers=Free" }
    "free"   { $heavy = "oc/deepseek-v4-flash-free"; $light = "oc/deepseek-v4-flash-free";  Write-Host "  [Free] all Free max hemat" }
    "custom" { Write-Host "  [Custom] edit .env manual, lalu run: opencode"; Read-Host "Press Enter"; exit 0 }
    default  { Write-Host "  Unknown: $Profile"; Read-Host "Press Enter"; exit 1 }
}

@"
# Farewell Orchestra — auto-generated by switch.ps1
NINEROUTER_API_KEY=sk_9router
ORCHESTRA_HEAVY_MODEL=$heavy
ORCHESTRA_LIGHT_MODEL=$light
"@ | Out-File -FilePath ".env" -Encoding ascii -NoNewline

Write-Host "  .env updated."
Write-Host ""
Write-Host "  Starting OpenCode..."
Write-Host ""
opencode
