@echo off
setlocal enabledelayedexpansion

:: ── Interactive mode (double-click / no args) ──────────────────
if "%1"=="" (
    echo.
    echo   ╔════════════════════════════════════════╗
    echo   ║     Farewell Orchestra — Profiles      ║
    echo   ╠════════════════════════════════════════╣
    echo   ║  1. Pro      orchestrator=Pro          ║
    echo   ║             workers=Flash              ║
    echo   ║                                        ║
    echo   ║  2. Flash    orchestrator=Flash        ║
    echo   ║             workers=Free               ║
    echo   ║                                        ║
    echo   ║  3. Free     all Free (max hemat)      ║
    echo   ║                                        ║
    echo   ║  4. Custom   edit .env manual          ║
    echo   ╚════════════════════════════════════════╝
    echo.
    set /p choice="  Pilih [1-4]: "

    if "!choice!"=="1" set ARG=pro
    if "!choice!"=="2" set ARG=flash
    if "!choice!"=="3" set ARG=free
    if "!choice!"=="4" set ARG=custom
    if "!ARG!"=="" (
        echo  Invalid choice
        pause
        exit /b 1
    )
) else (
    set ARG=%1
)

:: ── Profile mapping ────────────────────────────────────────────
if /i "!ARG!"=="pro" (
    set ORCHESTRA_HEAVY_MODEL=ocg/deepseek-v4-pro
    set ORCHESTRA_LIGHT_MODEL=ocg/deepseek-v4-flash
    echo  [Pro] orchestrator=Pro  ^|  workers=Flash
) else if /i "!ARG!"=="flash" (
    set ORCHESTRA_HEAVY_MODEL=ocg/deepseek-v4-flash
    set ORCHESTRA_LIGHT_MODEL=oc/deepseek-v4-flash-free
    echo  [Flash] orchestrator=Flash  ^|  workers=Free
) else if /i "!ARG!"=="free" (
    set ORCHESTRA_HEAVY_MODEL=oc/deepseek-v4-flash-free
    set ORCHESTRA_LIGHT_MODEL=oc/deepseek-v4-flash-free
    echo  [Free] all Free max hemat
) else if /i "!ARG!"=="custom" (
    echo  [Custom] edit .env manual, lalu run: opencode
    pause
    exit /b 0
) else (
    echo  Unknown: !ARG!   Use: pro ^| flash ^| free ^| custom
    pause
    exit /b 1
)

:: ── Write .env ─────────────────────────────────────────────────
(
    echo # Farewell Orchestra — auto-generated by switch.bat
    echo NINEROUTER_API_KEY=sk_9router
    echo ORCHESTRA_HEAVY_MODEL=!ORCHESTRA_HEAVY_MODEL!
    echo ORCHESTRA_LIGHT_MODEL=!ORCHESTRA_LIGHT_MODEL!
) > .env

echo  .env updated ^(ORCHESTRA_HEAVY_MODEL=!ORCHESTRA_HEAVY_MODEL!^)
echo  .env updated ^(ORCHESTRA_LIGHT_MODEL=!ORCHESTRA_LIGHT_MODEL!^)
echo.
echo  Run: opencode
echo.
pause
endlocal
