"""
check-links.py — Verify project doc integrity.

Checks:
1. Formal markdown links [text](path) — target exists
2. Informal file refs like `path/to/file.md` — file exists
3. file:line refs like `file.md:42` — line number in range when file exists

Excludes:
- Forward refs: files that will be generated (PRD.md, Architecture.md, etc.)
- Template refs: files inside templates/ referenced by bootstrap-project skill

Usage:  python .opencode/scripts/check-links.py
Exit:   0 if all OK, 1 if broken references found
"""

import os, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent  # farewell-orchestra/
EXCLUDES_DIRS = {
    "node_modules",
    ".git",
    "source",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
}
VERBOSE = "--verbose" in sys.argv

# Known forward references — files that DON'T exist yet but are valid references
# (generated by bootstrap-project skill or created during project setup)
FORWARD_REFS = {
    "sub-project.md",
    "PRD.md",
    "Architecture.md",
    "Design.md",
    "Schema.md",
    "Rules.md",
    "API_Contract.md",
    "Tasks.md",
    "Tests.md",
    "Context.md",
    "debug.md",
    "docs/Tasks.md",
    "CODING_STANDARDS.md",
    "CONTRIBUTING.md",
    "docs/glossary.md",
    "architecture.md",
    "docs-template.md",
}

# Known vault files — refs written without prefix (e.g. bare "Lessons.md")
# are valid; they live in Farewell-Knowlage/
VAULT_REFS = {"Lessons.md", "Session.md", "Decisions.md"}

# Known deleted files — refs to files intentionally removed (historical
# records like TRAINING.md "Sudah Dikerjakan" log); skip, they will never exist
DELETED_REFS = {"workflows/cross-project.md", "protocols/agent-communication.md"}

# Files where reference-like patterns are narrative prose, not file refs
NARRATIVE_FILES = {"check.md"}

# Patterns
LINK_RE = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)]+)\)")  # [text](path)
FILE_REF_RE = re.compile(
    r"(?:`)?([\w./\\-]+\.md)(?::(\d+))?(?:`)?"
)  # file.md or file.md:42


def is_excluded(p: Path) -> bool:
    for part in p.parts:
        if part in EXCLUDES_DIRS:
            return True
    return False


def find_md_files() -> list[Path]:
    files = []
    for p in ROOT.rglob("*.md"):
        if not is_excluded(p):
            files.append(p)
    return sorted(files)


def resolve_md_path(ref: str, source_dir: Path) -> Path | None:
    """Resolve a .md file reference relative to source_dir or ROOT."""
    # Try relative to source dir first
    candidate = (source_dir / ref).resolve()
    if candidate.exists():
        return candidate
    # Try relative to project root
    candidate = (ROOT / ref).resolve()
    if candidate.exists():
        return candidate
    return None


def strip_code_blocks(content: str) -> str:
    """Remove fenced code blocks (```...```) from content before checking."""
    return re.sub(r"```.*?```", "", content, flags=re.DOTALL)


def main():
    md_files = find_md_files()
    print(f"[LINK-CHECK] Scanning {len(md_files)} markdown files...")

    broken = []
    total_md_links = 0
    total_file_refs = 0

    for filepath in md_files:
        rel = filepath.relative_to(ROOT)
        content = filepath.read_text(encoding="utf-8")
        # Strip code blocks to avoid false positives
        content_clean = strip_code_blocks(content)
        source_dir = filepath.parent

        # === Check 1: Formal markdown links ===
        for match in LINK_RE.finditer(content_clean):
            link_text = match.group(1)
            link_target = match.group(2)
            total_md_links += 1

            if link_target.startswith(("http://", "https://", "ftp://", "mailto:")):
                continue
            if link_target.startswith("#"):
                continue

            # Strip anchor/section
            clean_target = link_target.split("#")[0].split("?")[0]
            if not clean_target:
                continue

            resolved = resolve_md_path(clean_target, source_dir)
            if resolved is None:
                line_no = content[: match.start()].count("\n") + 1
                broken.append(
                    f"  BROKEN {rel}:{line_no} — link '{link_target}' -> NOT FOUND"
                )

        # === Check 2: Informal file.md references ===
        # Skip narrative files (check.md has historical prose refs)
        if filepath.name in NARRATIVE_FILES:
            continue
        # Filter to avoid matching code blocks, URLs, and false positives
        for match in FILE_REF_RE.finditer(content_clean):
            ref_path = match.group(1)
            ref_line = match.group(2)
            total_file_refs += 1

            # Skip known non-md file extensions that happen to match pattern
            if not ref_path.endswith(".md"):
                continue

            # Skip self-references
            if ref_path == filepath.name:
                continue

            # Skip node_modules references
            if "node_modules" in ref_path:
                continue

            # Skip known forward refs (files that will be generated)
            if (
                ref_path in FORWARD_REFS
                or any(ref_path.endswith(f"/{f}") for f in FORWARD_REFS)
                or ref_path in VAULT_REFS
                or any(ref_path.endswith(f"/{v}") for v in VAULT_REFS)
                or ref_path in DELETED_REFS
                or any(ref_path.endswith(f"/{d}") for d in DELETED_REFS)
            ):
                continue

            # Resolve relative to source dir then project root
            resolved = resolve_md_path(ref_path, source_dir)
            line_no = content[: match.start()].count("\n") + 1
            if resolved is None:
                broken.append(
                    f"  BROKEN {rel}:{line_no} — ref '{ref_path}' -> NOT FOUND"
                )
            elif ref_line:
                # Optionally verify line number exists
                try:
                    target_lines = len(
                        resolved.read_text(encoding="utf-8").splitlines()
                    )
                    if int(ref_line) > target_lines:
                        broken.append(
                            f"  BROKEN {rel}:{line_no} — ref '{ref_path}:{ref_line}' -> line {ref_line} > {target_lines} total"
                        )
                except ValueError:
                    pass

    # Report
    total = total_md_links + total_file_refs
    if broken:
        print(f"[LINK-CHECK] FAIL — {len(broken)} broken ref(s) out of {total} total:")
        for b in broken:
            print(b)
        sys.exit(1)
    else:
        print(
            f"[LINK-CHECK] OK — {total} references verified ({total_md_links} links, {total_file_refs} file refs), 0 broken"
        )
        sys.exit(0)


if __name__ == "__main__":
    main()
